[package]
name = "fill-the-damn-bot"
version = "0.1.0"
authors = ["/alex/ <Al3k5@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.8.0"
rand = "0.8.3"
clipboard = "0.5.0"
